services:

  postgres:
    image: 'postgres:latest'
    container_name: 'monote_postgres'
    environment:
      - 'POSTGRES_DB=monote_postgres'
      # TODO 1/2: Enter your Password for PostgreSQL database here
      - 'POSTGRES_PASSWORD=YOUR_POSTGRESQL_PASSWORD'
      # TODO 2/2: Enter your Username for PostgreSQL database here
      - 'POSTGRES_USER=YOUR_POSTGRESQL_USERNAME'
      - 'TZ=Asia/Ho_Chi_Minh'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: 'redis:latest'
    container_name: 'monote_redis'
    environment:
      - 'TZ=Asia/Ho_Chi_Minh'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
